### ISSUE TITLE
Plain text access passwords

### ISSUE THREAD

**Issue by TheSerapher** [sous-chefs/percona#26]
Not an issue per say:

When setting up a Percona Server a file is created to properly set the user passwords:

https://github.com/phlipper/chef-percona/blob/master/recipes/access_grants.rb#L4

Now from a security standpoint, even when setting the file permissions very restrictive to root only, this is not a good idea.

I am wondering if there is another solution than writing out all granted permissions into a template and then loading this file via mysql.

Besides the fact that we have a plain text file with all main passwords on disk we also were unable to change the root password. Could this be a limitation by chef itself? Once we update the password the machine does not have the old root password available in order to setup a new password, correct?

I am open for suggestions how this could be solved.

**Comment by whysthatso** [comment]
maybe giving the option for chef vault would be possible?

**Comment by phlipper** [comment]
@whysthatso `chef-vault` support has been added in #261.

**Comment by Xorima** [comment]
Closing as old issue, please reopen if this is still a problem?
