### ISSUE TITLE
mysql2 chef gem failing to install

### ISSUE THREAD

**Issue by vgirnet** [sous-chefs/percona#380]
### Cookbook version
[0.6.14] - actually, latest master branch

### Chef-client version
[14.2]

### Platform Details
[CentOS 7]

### Scenario:
[Install mysql2 Chef Gem]

### Steps to Reproduce:
[If you are filing an issue what are the things we need to do in order to repro your problem? How are you using this cookbook or any resources it includes?]

- Including 'percona::server' in run list:
```
include_recipe 'percona::server'
mysql2_chef_gem 'default' do
  provider Chef::Provider::Mysql2ChefGem::Percona
  action :install
end
```

- In 'metadata.rb' I have:
```
depends     'percona'
depends     'mysql2_chef_gem'
```

- In 'Berksfile' I have:
```
source 'https://supermarket.chef.io'
metadata
cookbook 'percona', git: 'https://github.com/sous-chefs/percona.git'
```

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]
To have Percona Server and mysql2 gem installed

### Actual Result:
[What actually happens after the reproduction steps? Include the error output or a link to a gist if possible.]
mysql2 gem failing to install due to missing development libraries. 
------------
```
[2018-07-19T11:13:34+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: mysql2_chef_gem_mysql2_chef_gem_mysql[default] (tkis_percona::default line 18) had an error: Mixlib::ShellOut::ShellCommandFailed: chef_gem[mysql2] (/tmp/kitchen/cache/cookbooks/percona/libraries/provider_mysql2_chef_gem.rb line 19) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
       ---- Begin output of /opt/chef/embedded/bin/gem install mysql2 -q --no-rdoc --no-ri -v "0.5.2" --source=https://www.rubygems.org ----
       STDOUT: Building native extensions. This could take a while...
       STDERR: ERROR:  Error installing mysql2:
       	ERROR: Failed to build gem native extension.
       
           current directory: /opt/chef/embedded/lib/ruby/gems/2.5.0/gems/mysql2-0.5.2/ext/mysql2
       /opt/chef/embedded/bin/ruby -r ./siteconf20180719-15481-d9i0j2.rb extconf.rb
       checking for rb_absint_size()... yes
       checking for rb_absint_singlebit_p()... yes
       checking for rb_wait_for_single_fd()... yes
       checking for -lmysqlclient... no
       -----
       mysql client is missing. You may need to 'apt-get install libmysqlclient-dev' or 'yum install mysql-devel', and try again.
```
-------------

Adding 
`package "Percona-Server-devel-#{node['percona']['version'].tr('.', '')}"
`
to the recipe before calling 'mysql2_chef_gem' is solving the issue.

**Comment by Xorima** [comment]
Hi @vgirnet 

We have released numerous fixes for this cookbook since this issue was raised, could you check if this is still an issue please?

Thanks !

**Comment by vgirnet** [comment]
Hello,

I have checked with latest version, mysql2 gem was installed correctly from the first run. 

I've got other issues, not related to this one:
There are 2 singing keys for Percona RPMS. The second one worked for newer packages. 
https://www.percona.com/downloads/RPM-GPG-KEY-percona - For Percona RPM packages signed on or before December 20th, 2018
https://repo.percona.com/yum/PERCONA-PACKAGING-KEY- For Percona RPM packages signed on or after December 20th, 2018
https://www.percona.com/downloads/

Looks like you need to adjust repositories configuration as well.

**Comment by Xorima** [comment]
could you open new issues for those ones if not already open please and close this one off if completed @vgirnet ?

Thanks
