### ISSUE TITLE
Root accounts left with no passwords despite using encrypted data bags 

### ISSUE THREAD

**Issue by ciphersys** [sous-chefs/percona#58]
After using percona::server with appropriately set encrypted data bags, I tested it worked with mysql -u root. I was able to login. I also tested with mysql -u root -p which also worked. Not understanding what was happening, I investigated further:

mysql> use mysql;
mysql> select host,user,password from user;
+-----------+------------------+-------------------------------------------+
| host      | user             | password                                  |
+-----------+------------------+-------------------------------------------+
| localhost | root             | redacted|
| myhostname       | root             |                                           |
| 127.0.0.1 | root             |                                           |
| ::1       | root             |                                           |
| localhost | debian-sys-maint |redacted |
+-----------+------------------+-------------------------------------------+
5 rows in set (0.00 sec)

It looks like the line from percona/recipes/configure_server.rb which performs the update: 

configure_server.rb:  command "mysqladmin --user=root --password='' password '#{passwords.root_password}'"

...only applies the change to root@"localhost", but leaves other open root entries. 

This is a nasty security issue. 

I'd like to know if there's something in an attribute i can do to fix this, or if I need to write a separate recipe to clear out any accounts without passwords (or apply the password across all entries).

This was on Ubuntu 12.04 for reference.

**Comment by sethlindberg** [comment]
I have the issue and I'm using the default named bag.  It's on RHEL if that is an issue.

**Comment by Xorima** [comment]
Closing as old issue, please reopen if this is still a problem?
